name: Validate References

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_references:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # 修改为你想要使用的Python版本

    - name: Validate References
      run: python validate_references.py